# Generated by Django 5.0.9 on 2024-09-17 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchimage',
            name='batch_upload',
        ),
        migrations.DeleteModel(
            name='BatchUpload',
        ),
    ]
