# Generated by Django 5.0.9 on 2024-09-17 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0002_remove_batchimage_batch_upload_delete_batchupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchimage',
            name='flower_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='ProcessedResult',
        ),
    ]
