# Generated by Django 5.0.9 on 2024-09-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0003_batchimage_flower_count_delete_processedresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchimage',
            name='processed',
        ),
        migrations.AddField(
            model_name='batchimage',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
