# Generated by Django 5.0.9 on 2024-09-17 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0004_remove_batchimage_processed_batchimage_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchimage',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='batchimage',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/images/'),
        ),
    ]
